### PR TITLE
PAL-1077 updated image repository property

### PR DESCRIPTION
**Pull request by pd104923**
- Updated image repository value in parent pom

### CODE REVIEW

**Review by m78233 — COMMENTED** [review]
Same question as for the one in Palisade-Readers.  Reads like gchq/palisade will be the repository.  The "-" will be something we need in the related functionality.  Can we just have this describe the image repository.

**Comment by pd104923** [comment]
> Same question as for the one in Palisade-Readers. Reads like gchq/palisade will be the repository. The "-" will be something we need in the related functionality. Can we just have this describe the image repository.

This question has been answered within the readers repo.

**Review by developer01189998819991197253 — DISMISSED** [review]

**Comment by ac74475** [comment]
Given we dont build any images in the clients repo, I dont think we need to specify an image.repository maven property. Therefore can we remove the property all together from this repo.

**Review by m78233 — APPROVED** [review]

**Comment by pd104923** [comment]
> Given we dont build any images in the clients repo, I dont think we need to specify an image.repository maven property. Therefore can we remove the property all together from this repo.

The property has been removed from the parent pom.

**Review by ac74475 — APPROVED** [review]

**Pull request merged**
